### ISSUE TITLE
How to download digital twin data at a different resolution?

### ISSUE THREAD

**Issue by XLY43** [facebookresearch/ATEK#25]
Hi, I am trying to download the digital twin data from data store using the following command:
  
python3 ./tools/atek_wds_data_downloader.py \
  --config-name efm \
  --input-json-path .pathto/AriaDigitalTwin_ATEK_download_urls.json\
  --output-folder-path ./training_output/ \
  --train-val-split-ratio 0.8 \
  --download-wds-to-local --max-num-sequences 10

The downloaded data got resized to [240,240] but my model needs [512, 512]. Can I set the resolution in some ways? I tried modifying the "processor" setting in the AriaDigitalTwin_ATEK_download_urls.json setting but it didn't seem to work. 

Thanks for your help.

**Comment by echo-xiao9** [comment]
Hi, thanks for reaching out. We prepare the data following this [config](https://github.com/facebookresearch/ATEK/blob/main/atek/configs/efm_preprocess_base.yaml). The target_camera_resolution for rgb is [240, 240], as indicated in the configuration file. 

To prepare dataset with specific resolution, you can change the config and go through data preproce
ssing by following [preprocessing doc](https://github.com/facebookresearch/ATEK/blob/main/docs/preprocessing.md). You can download the original ADT data [here](https://www.projectaria.com/datasets/adt/)

Feel free to let us know if  you have any other questions.
